version: '3.3'

services:
  contractor-db:
    container_name: contractor-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contractors
    volumes:
      - contractor-db-data:/var/lib/postgresql/data
    networks:
      - docker-network-internal

  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    depends_on:
      - contractor-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - docker-network-internal
      - docker-network


volumes:
  contractor-db-data:

networks:
  docker-network-internal:
    internal: true
  docker-network: