openapi: 3.0.3
info:
  title: Телеграмм бот ЦТК
  version: 0.0.1
servers:
  - url: http://45.135.234.35:8082
tags:
  - name: users
paths:
  /users/{id}/clients:
    get:
      tags:
        - users
      summary: "Клиенты пользователя"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
            example: 1
        - name: "size"
          in: query
          required: true
          schema:
            type: "integer"
            format: "int64"
            minimum: 1
            example: 1
        - name: "page"
          in: query
          required: false
          schema:
            type: "integer"
            format: "int64"
            minimum: 0
            example: 0
        - name: "name"
          in: query
          required: false
          description: Часть названия компании (без учета регистра)
          schema:
            type: string
            example: ооо ромаш
        - name: "clientStatusId"
          in: query
          required: false
          schema:
            type: "integer"
            format: "int64"
            minimum: 1
            example: 1
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserClientsDTO"
        '422':
          description: Невлидные данные, разделенные ;
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                status: 422
                message: Id пользователя должно быть не меньше 1; Номер страницы должен быть не меньше 0; Размер страницы должен быть не меньше 1; Id статуса клиента должно быть не меньше 1
  /users/{id}/personalAccount:
    get:
      tags:
        - users
      summary: Личный кабинет пользователя
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
            example: 1
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonalAccountDTO"
        '422':
          description: Невлидные данные.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                status: 422
                message: Id пользователя должно быть не меньше 1
components:
  schemas:
    AccountType:
      type: "object"
      properties:
        accountId:
          type: "integer"
          format: "int64"
          example: 2
        typeName:
          type: "string"
          enum:
            - "ZOOM"
            - "SIP"
    AccountDTO:
      type: "object"
      properties:
        accountId:
          type: "integer"
          format: "int64"
          example: 2
        login:
          type: "string"
          example: zoom_login
        password:
          type: "string"
          example: zoom123456
        accountType:
          $ref: "#/components/schemas/AccountType"
    PersonalAccountDTO:
      type: "object"
      properties:
        reward:
          type: number
          example: 200.12
        meetingsCount:
          type: "integer"
          format: "int64"
          example: 1
        ordersCount:
          type: "integer"
          format: "int64"
          example: 2
        accounts:
          type: "array"
          items:
            $ref: "#/components/schemas/AccountDTO"
    ErrorDTO:
      type: object
      properties:
        status:
          type: integer
          format: "int64"
        message:
          type: string
    ContactDTO:
      type: "object"
      properties:
        clientContactId:
          type: "integer"
          format: "int64"
          example: 1
        phoneNumber:
          type: "string"
          example: +375297654321
        description:
          type: "string"
          example: Рабочий - можно звонит с 8 до 17
    CallDTO:
      type: "object"
      properties:
        callId:
          type: "integer"
          format: "int64"
          example: 1
        localDate:
          type: "string"
          format: "date"
          example: 2024-01-14
        result:
          type: "string"
          example: Договорились о встрече
    MeetingDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1
        localDate:
          type: "string"
          format: "date"
          example: 2024-01-15
        result:
          type: "string"
          example: Не договорились
    ClientStatusDTO:
      type: "object"
      properties:
        clientStatusId:
          type: "integer"
          format: "int64"
          example: 1
        status:
          type: "string"
          enum:
            - "FAVORITE"
            - "RESERVED"
    UserClientsDTO:
      type: "object"
      properties:
        clientId:
          type: "integer"
          format: "int64"
          example: 1
        name:
          type: "string"
          example: ООО Ромашки и цветочки
        contacts:
          type: "array"
          items:
            $ref: "#/components/schemas/ContactDTO"
        calls:
          type: "array"
          items:
            $ref: "#/components/schemas/CallDTO"
        meetings:
          type: "array"
          items:
            $ref: "#/components/schemas/MeetingDto"
        clientStatus:
          $ref: "#/components/schemas/ClientStatusDTO"