spring:
  application:
    name: contractor
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/contractors
    username: postgres
    password: Traktaryst
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db.migration
springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false
server:
  port: 8080
file:
  storage: ./reports/